# Generated by Django 4.1.7 on 2023-03-04 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_remove_tasks_completed'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tasks',
        ),
    ]
